### ISSUE TITLE
QGIS 3 Girona

### ISSUE THREAD

**Issue by aourednik** [peterahlstrom/PointConnector#14]
Hi. 
Many thanks for developing this plugin.
Would you agree to update to a QGIS 3 version ? Currently, installing from zip triggers this traceback:

```python
Couldn't load plugin 'PointConnector' due to an error when calling its classFactory() method 

ImportError: No module named 'PyQt4' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/andre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PointConnector/__init__.py", line 34, in classFactory
    from .point_connector import PointConnector
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/andre/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PointConnector/point_connector.py", line 22, in 
    from PyQt4.QtCore import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named 'PyQt4'


Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
QGIS version: 3.0.2-Girona Girona, 307d082 
```

**Comment by rdbath** [comment]
I updated the plugin so it works in QGIS3. pending Pull Request https://github.com/peterahlstrom/PointConnector/pull/16

**Comment by peterahlstrom** [comment]
Thank you so much @rdbath for doing this! I haven't had any time to do the upgrade because of life, kids and all that.
Much appreciated!

**Comment by rdbath** [comment]
> I haven't had any time to do the upgrade because of life, kids and all that.

I know what you are talking about ;-) In my spare time I would probably also haven't found the time to do this but fortunately a colleague of mine wanted to use the plugin for his work so I was able to do the update during my working hours ;-) . After updating more than 15 plugins during the last weeks I got a bit of a routine so the update was done in less than two hours.

**Comment by peterahlstrom** [comment]
I'm sure many people are grateful for your efforts. :)
Uploading the plugin to QGIS plugins repository now!
